[package]
name = "hedwig"
version = "1.0.1"
authors = [
    "Aniruddha Maru <aniruddhamaru@gmail.com>",
    "Simonas Kazlauskas <hedwig@kazlauskas.me>"
]
edition = "2018"
repository = "https://github.com/standard-ai/hedwig-rust.git"
homepage = "https://github.com/standard-ai/hedwig-rust"
readme = "README.md"
description = "A simple message bus for Rust"
license = "Apache-2.0"
keywords = ["pubsub", "messagebus", "microservices"]
categories = ["asynchronous", "web-programming"]

[badges]
maintenance = { status = "actively-developed" }

[features]
default = []
# Publishers
google = ["base64", "yup-oauth2", "hyper", "http", "serde_json", "serde", "serde/derive", "uuid/serde"]
# Validators
json-schema = ["valico", "serde_json", "serde"]
protobuf = ["prost"]

[[example]]
name = "publish"
required-features = ["google", "json-schema"]

[dependencies]
futures-util = { version = "0.3", features = ["std"], default-features = false }
thiserror = { version = "1", default-features = false }
url = { version = "2", default-features = false }
uuid = { version = "^0.8", features = ["v4"], default-features = false }

serde = { version = "^1.0", optional = true, default-features = false }
serde_json = { version = "^1", features = ["std"], optional = true, default-features = false }
valico = { version = "^3.2", optional = true, default-features = false }
base64 = { version = "^0.12", optional = true, default-features = false }
http = { version = "^0.2", optional = true, default-features = false }
hyper = { version = "^0.13.1", optional = true, default-features = false }
yup-oauth2 = { version = "4", optional = true, default-features = false }
prost = { version = "0.6", optional = true, default-features = false }

[dev-dependencies]
hyper-tls = "0.4.0"
tokio = { version = "^0.2.4", features = ["macros"] }
serde = { version = "1", features = ["derive"] }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
